### PR TITLE
Do not install the geoff command

### PR DESCRIPTION
**Pull request by marcusk**
The geoff extension was removed in commit 3cd59da, but the geoff command is still installed. When run it prints an error:

`ImportError: No module named geoff.__main__`

If the geoff extension will not come back then I suggest that the geoff command should no longer be installed.

### CODE REVIEW

**Comment by technige** [comment]
Thanks, good spot.

**Comment by technige** [comment]
Could you re-raise this against the v4 branch?

**Comment by marcusk** [comment]
Sure, I've changed the base branch to v4.

**Comment by andriisoldatenko** [comment]
@marcusk Looks like you have failed tests, 
try to `git commit --allow-empty` to trigger rebuild of travis.

**Comment by marcusk** [comment]
@andriisoldatenko OK, now Travis reports that all checks have passed.

**Pull request merged**
